### ISSUE TITLE
Build conversion image in dockerhub and base worker image on it

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dist-git-to-source-git#114]
As @csomh pointed out in #112, we should base the worker image on the one defined in [Containerfile](https://github.com/packit/dist-git-to-source-git/blob/d0510bd22879419871ab489e1ba51b18188c30e3/Containerfile) because it needs to install the same package-dependencies.

This conversion image is not built publicly like we are building the worker. The task of this issue is to:
- [ ] build the conversion image publicly
- [ ] base the worker image on the conversion one

**Comment by csomh** [comment]
sync, pls
