### ISSUE TITLE
no metadata in commits with %autosetup -S git

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#34]
packit srpm fails for packages using `%autosetup -S git`.

Error message: `packit.exceptions.PackitSRPMException: Preparing of the upstream to the SRPM build failed: Failed to parse SPEC file: error: patch 1 defined multiple times`

The commits don't include metadata:
```
commit 34baccb5764cb2a5f2b37e01e0d4d7d438e42a99 (HEAD -> c8s)
Author: rpm-build <rpm-build>
Date:   Fri Aug 21 14:42:42 2020 +0000

    0004-invalid-IPv4-address.patch
```

packit srpm adds it to spec:
```
+# PATCHES FROM SOURCE GIT:
+
+# 0001-man-tcpdump-and-tcpslice-have-manpages-in-man8.patch
+# Author: rpm-build <rpm-build>
+Patch0001: 0001-0001-man-tcpdump-and-tcpslice-have-manpages-in-man8..patch
```

Example packages `{'logrotate', 'gnome-remote-desktop', 'librsvg2', 'mutter', 'virt-manager', 'abrt', 'libpcap', 'libreport', 'gnome-abrt', 'vhostmd', 'setools', 'vsftpd', 'ghostscript', 'frr', 'webkit2gtk3', 'bluez'}`

**Comment by TomasTomecek** [comment]
```
%prep
# http://www.rpm.org/wiki/PackagerDocs/Autosetup
# Default '__scm_apply_git' is 'git apply && git commit' but this workflow
# doesn't allow us to create a new file within a patch, so we have to use
# 'git am' (see /usr/lib/rpm/macros for more details)
%define __scm_apply_git(qp:m:) %{__git} am
%autosetup -S git
```
libreport /o\
