### ISSUE TITLE
content of BUILD not a git repository

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#37]
For some packages, we get 
```
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /workdir/rpms/autofs/BUILD/autofs-5.1.4
```

git.Repo expect `.git` in the path.

Example packages ['autofs', 'autogen', 'socat'] - c8 branch

**Comment by TomasTomecek** [comment]
those packages are doing `%setup` and `%patch` - the true old school

the problem is that nor %setup nor %patch are defined in /usr/lib/rpm so d2s is not creating a git repo nor applying metadata

let me see how we can hijack this

**Comment by csomh** [comment]
> those packages are doing `%setup` and `%patch` - the true old school
> 
> the problem is that nor %setup nor %patch are defined in /usr/lib/rpm so d2s is not creating a git repo nor applying metadata
> 
> let me see how we can hijack this

A few weeks ago this was working by [replacing `%setup` with `%gitsetup`](https://github.com/packit/dist-git-to-source-git#using-rpmbuild--bp-to-generate-source-git-repositories). Was this changed in any way?
