### ISSUE TITLE
conditional patching - package tracker issue

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#57]
Tracker for packages that apply patches conditionally and the srpm build ends with `.patch: No such file or directory`.

- c8s: `bpftrace`, `gdb`, `java-1.8.0-openjdk`, `mozjs52`, `mozjs60`, `qt5-qtbase`, `qt5-qttools`, `sqlite`, `zlib`
- c8: `icu`, `java-1.8.0-openjdk`, `kyotocabinet`, `mingw-freetype`, `mod_fcgid`, `perl-Dist-CheckConflicts`, `perl-ExtUtils-Config`, `perl-Package-Generator`, `perl-Package-Stash`, `perl-Package-Stash-XS`, `perl-Sub-Exporter-Progressive`, `pidgin`, `postfix`, `python-botocore`, `qt5-qttools`, `rrdtool`, `sqlite`, `strace`, `tinyxml2`, `jasper` (needs cmake-rpm-macros and cmake installed in dist2src), `valgrind`, `check`, `xinetd`, `zlib`, `compat-libgfortran-48`, `binutils`, `gdb`, `ghc`, `ghc-extra`, `libpinyin`, `libtool`, `libvncserver`

**Comment by TomasTomecek** [comment]
The problem seems to be that a patch is defined, not applied and not present on the disk and such spec file fails to be parsed.

We could solve this by creating empty commits for patches which are not being applied (should be easy to do).

**Comment by dhodovsk** [comment]
Repositories were  created for 
mod_fcgid
qt5-qttools
rrdtool
check
zlib
gdb
libtool
libvncserver

Other packages hit different error.
