### ISSUE TITLE
git ignores .packit or spec

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#66]
Failure: `paths are ignored by one of your .gitignore files`

Packages:
 - c8s: `haproxy`, `libbpf`, `libpfm`, `mdevctl`, `pmdk`
 - c8: `iptraf-ng`, `libbpf`, `libpfm`, `libpmemobj-cpp`, `nvml`, `pmdk`, `haproxy`

**Comment by fweimer** [comment]
glibc had a similar issue, if I recall correctly, but is not listed here. Is this because we have a manual conversion?

The probable fix for this issue is to use `git add -f` in place of `git add`.

**Comment by codonell** [comment]
Does this issue block the automatic importing of glibc's `c8s` branch? If it does then that would be a shame. We want to start experimenting with this and keeping `c8s` updated is relevant and important.

**Comment by TomasTomecek** [comment]
@codonell @fweimer thanks for the feedback!

should be fixed by #90

**Comment by TomasTomecek** [comment]
@dhodovsk should we reopen? do we have repos for all of these?

**Comment by dhodovsk** [comment]
All repositories for packages mentioned in the error description now exist :)
