### ISSUE TITLE
No subdirectory found in BUILD

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#73]
The issue for failures not caused by https://github.com/packit/dist-git-to-source-git/issues/54

Packages:
 - c8s: `filesystem`, `qt5-doc`
 - c8: `perl-srpm-macros`, `qt5-doc`, `rootfiles`, `rteval-loads`, `spice-client-win`, `spice-qxl-xddm`, `spice-vdagent-win`, `centos-release`, `filesystem`, `appstream-data`, `go-compilers`, `google-roboto-slab-fonts`

**Comment by dhodovsk** [comment]
Most likely related to https://github.com/packit/dist-git-to-source-git/issues/46

**Comment by dhodovsk** [comment]
Skip these packages.

**Comment by dhodovsk** [comment]
After checking the spec files of packages in this issue, it's clear this is a duplicate of https://github.com/packit/dist-git-to-source-git/issues/46

**Comment by TomasTomecek** [comment]
Agreed, since there is no "code" for these packages, it doesn't make much sense to focus on these.
