### ISSUE TITLE
`convert gnome-settings-daemon`: patches are not handled properly

### ISSUE THREAD

**Issue by TomasTomecek** [packit/dist-git-to-source-git#9]
```
$ dist2src.py -v convert {rpms,source-git}/gnome-settings-daemon:c8s
```

I expected all patches to be turned into commits and dropped from SOURCES dir

Instead:
* the patches were still present in the spec
* they were also present in the SOURCES dir
* and no git commits were done

**Comment by TomasTomecek** [comment]
https://github.com/rebase-helper/rebase-helper/issues/798 the main cause

**Comment by dhodovsk** [comment]
It's ok now (do we know why?) - https://git.stg.centos.org/source-git/gnome-settings-daemon/commits/c8s :)

**Comment by TomasTomecek** [comment]
nice!
